name: bun-hono-ddd-template

services:
  postgres:
    container_name: bun-hono-ddd-template-postgres
    image: postgres:17-alpine
    user: "0:0"
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - bun-hono-ddd-template-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  bun-hono-ddd-template-network:
    name: bun-hono-ddd-template-network
    driver: bridge
